manifest_version: 2
id: discord
ecs_version: "9.4.0-dev"
target: "Discord"
last_updated: "2025-02-03"

files:
  - id: "discord_analytics_login"
    path: "activity/analytics/events-2025-00000-of-00001.json"
    parser:
      format: "jsonl"



views:
  - file:
      id: "discord_analytics_login"
      where: {source: "event_type", op: "==", value: "session_start_success"}
    static:
      event.action: "user_login_success"
      event.kind: "event"
      event.category: ["authentication"]
      event.type: ["start"]
      event.outcome: "success"
    fields:
      - {target: "@timestamp", source: "timestamp", type: "datetime"}
      - {target: "client.ip", source: "ip", type: "string"}
      - {target: "user_agent.original", source: "browser", type: "string"}
      - {target: "device.model.name", source: "device", type: "string"}
      - {target: "PLACEHOLDER", source: "os", type: "string"}
      - {target: "PLACEHOLDER", source: "os_version", type: "string"}
